<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3y7QP9F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3y7QP9F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3y7QP9F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3y7QP9F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3y7QP9F\App_KernelDevDebugContainer([
    'container.build_hash' => '3y7QP9F',
    'container.build_id' => '86d97e94',
    'container.build_time' => 1631280829,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3y7QP9F');
